---
title: "rosenzweig_macarthur_apparent_competition"
author: "Matthew Barbour"
date: "February 26, 2015"
output: word_document
---

Create model

Load required R libraries for running the models.
```{r load libraries}
require(deSolve)
require(seqinr)
```

```{r}
## Rosenzweig-MacArthur consumer-resource model 
# assumes logistic resource growth and a type 2 functional response by the consumer (i.e. consumption rate saturates with resource density) and predator. This function is necessary for the ordinary differential equation solver, ode() 
RM_apparent <- function(t,y,p) {
  # t,y,p is the necessary format for solving using the ode() function in R
  R1 <- y[1]
  R2 <- y[2]
  C <- y[3]
  with(as.list(p), {
    dR1.dt <- r1 * R1 * (1 - R1 / K1) - a1 * C * R1 / (1 + a1 * h1 * R1)
    dR2.dt <- r2 * R2 * (1 - R2 / K2) - a2 * C * R2 / (1 + a2 * h2 * R2)
    dC.dt <- e1 * a1 * C * R1 / (1 + a1 * h1 * R1) + e2 * a2 * C * R2 / (1 + a2 * h2 * R2)  - dC * C 
    return(list(c(dR1.dt, dR2.dt, dC.dt)))
  })
}
```

Set intial state variable (Resource and Consumer densities) for running the model. Note that it is not immediately clear what their initial state variable were so I just played around until I got ones that were close.
```{r}
# state variable values (initial values at beginning of "experiments")
R1 <- R2 <- 1
C <- 0.2
i.state <- c(R1 = R1, R2 = R2, C = C) 
```


```{r}
# parameter values from Fig. 7.3 in Food Webs by Kevin McCann
r1 <- r2 <- 1 # per capita rate of increase in resource
K1 <- K2 <- 2 # carrying capacity
e1 <- e2 <- 0.5 # predator conversion efficiency
h1 <- 0.05 # handling time
h2 <- 0.05
dC <- 0.5 # mortality rate of predator
a1 <- a2 <- 1.1 # attack rate of Consumer

# run the experiment. This experiment essentially solves the model at the initial C and R densities, and takes the new C and R densities and reruns the model, and so on until the end of time.
p.rm1 <- c(r1 = r1, r2 = r2, 
           K1 = K1, K2 = K2,
           e1 = e1, e2 = e2, 
           a1 = a1, a2 = a2,
           h1 = h1, h2 = h2, 
           dC = dC) # create a vector for the parameters for experiment #1
 
Time <- 400 # set time scale
rm1 <- ode(i.state, 1:Time, RM_apparent, p.rm1) # run the experiment 

# replicate Fig. 3a
matplot(rm1[,1], rm1[,c(2,3,4)],
        type = "l", ylab="Density", xlab="Time", ylim=c(0, C*15), main = "Apparent Competition")
legend("top", c("R1","R2", "C"), lty=1:3, col=1:3, bty="n")
```