---
title: "rosenzweig-macarthur food chain"
author: "Matthew Barbour"
date: "February 25, 2015"
output: word_document
---

Creat model

Load required R libraries for running the models.
```{r load libraries}
require(deSolve)
require(seqinr)
```

```{r}
## Rosenzweig-MacArthur consumer-resource model 
# assumes logistic resource growth and a type 2 functional response by the consumer (i.e. consumption rate saturates with resource density) and predator. This function is necessary for the ordinary differential equation solver, ode() 
RM_chain <- function(t,y,p) {
  # t,y,p is the necessary format for solving using the ode() function in R
  R <- y[1]
  C <- y[2]
  P <- y[3]
  with(as.list(p), {
    dR.dt <- r * R * (1 - R / K) - aC * C * R / (1 + aC * hC * R)
    dC.dt <- eC * aC * C * R / (1 + aC * hC * R) - dC * C - aP * C * P / (1 + aP * hP * P)
    dP.dt <- eP * aP * C * P / (1 + aP * hP * P) - dP * P
    return(list(c(dR.dt, dC.dt, dP.dt)))
  })
}
```

Set intial state variable (Resource and Consumer densities) for running the model. Note that it is not immediately clear what their initial state variable were so I just played around until I got ones that were close.
```{r}
# state variable values (initial values at beginning of "experiments")
R <- 1
C <- 0.2
P <- 0.05
i.state <- c(R = R, C = C, P = P) 
```

By altering attack rate, it is easy to recover a classic trophic cascade.
```{r}
# parameter values from Fig. 7.3 in Food Webs by Kevin McCann
r <- 1 # per capita rate of increase in resource
K <- 2 # carrying capacity
eP <- eC <- 0.5 # predator conversion efficiency
hP <- hC <- 0.05 # handling time
dC <- 0.5 # mortality rate of predator
dP <- 0.3
aC <- 1.8 # attack rate of Consumer
aP <- 1.1 # attack rate of predator

# run the experiment. This experiment essentially solves the model at the initial C and R densities, and takes the new C and R densities and reruns the model, and so on until the end of time.
p.rm1 <- c(r = r, K = K, eP = eP, eC = eC, aC = aC, aP = aP,
           hC = hC, hP = hP, dC = dC, dP = dP) # create a vector for the parameters for experiment #1
 
Time <- 1000 # set time scale
rm1 <- ode(i.state, 1:Time, RM_chain, p.rm1) # run the experiment 

# replicate Fig. 3a
matplot(rm1[,1], rm1[,c(2,3,4)],
        type = "l", ylab="Density", xlab="Time", ylim=c(0, C*15), main = "Food Chain")
legend("top", c("R","C","P"), lty=1:3, col=1:3, bty="n")
```